// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-web-base/internal/handlers"
	"go-web-base/internal/services"
	"go-web-base/internal/stores"
	"go-web-base/internal/types"
)

// Injectors from wire.go:

func InitializeTodoHandler(store map[string]*types.Todo) *handlers.TodoHandler {
	todoStore := stores.NewTodoStore(store)
	todoService := services.NewTodoService(todoStore)
	todoHandler := handlers.NewTodoHandler(todoService)
	return todoHandler
}
